module.exports = {
  apps: [
    {
      name: "nextjs-premier",
      cwd: "apps/premier-printing",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      exec_mode: "cluster",
      instances: "5",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "3",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-pythias",
      cwd: "apps/pythias",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3002",
      exec_mode: "cluster",
      instances: "1",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "10",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-storefront",
      cwd: "apps/pythias-storefront",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3020",
      exec_mode: "cluster",
      instances: "2",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null,
      error: null,
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "3",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      max_memory_restart: "3G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *",
    },
    {
      name: "nextjs-po",
      cwd: "apps/po",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      exec_mode: "cluster",
      instances: "5",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "10",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-platform",
      cwd: "apps/pythias-platform",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3010",
      exec_mode: "cluster",
      instances: "2",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null,
      error: null,
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "3",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      max_memory_restart: "3G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *",
    },
    {
      name: "pull-orders",
      cwd: "apps/premier-printing",
      script: "scripts/runPullOrders.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 * * * *", // every hour
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/pull-orders-out.log",
      error_file: "logs/pull-orders-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "tracking-premier-printing",
      cwd: "apps/premier-printing",
      script: "scripts/runTracking.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */6 * * *", // every 6 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/tracking-premier-out.log",
      error_file: "logs/tracking-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "inventory-maintenance-po",
      cwd: "apps/po",
      script: "scripts/runInventoryMaintenance.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "*/15 * * * *", // every 15 min — reconcile "ordered" flags + stock status to active-PO truth
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/inventory-maintenance-po-out.log",
      error_file: "logs/inventory-maintenance-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "tracking-po",
      cwd: "apps/po",
      script: "scripts/runTracking.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */6 * * *", // every 6 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/tracking-po-out.log",
      error_file: "logs/tracking-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "blanks-forecast-premier",
      cwd: "apps/premier-printing",
      script: "scripts/runBlankForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/blanks-forecast-premier-out.log",
      error_file: "logs/blanks-forecast-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "blanks-forecast-po",
      cwd: "apps/po",
      script: "scripts/runBlankForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/blanks-forecast-po-out.log",
      error_file: "logs/blanks-forecast-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "forecast-premier",
      cwd: "apps/premier-printing",
      script: "scripts/runForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/forecast-premier-out.log",
      error_file: "logs/forecast-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "forecast-po",
      cwd: "apps/po",
      script: "scripts/runForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/forecast-po-out.log",
      error_file: "logs/forecast-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "commerce-catalog-sync",
      cwd: "apps/pythias-platform",
      script: "scripts/importPremierCatalog.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */12 * * *", // every 12 hours — sync Premier catalog + pricing into Commerce Cloud
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3010,
      },
      out_file: "logs/commerce-catalog-sync-out.log",
      error_file: "logs/commerce-catalog-sync-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "auto-reorder-platform",
      cwd: "apps/pythias-platform",
      script: "scripts/runAutoReorder.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 10 * * *", // daily 10:00 UTC (6am EST) — restock low catalog stock for opted-in sellers
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3010,
      },
      out_file: "logs/auto-reorder-platform-out.log",
      error_file: "logs/auto-reorder-platform-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "dropship-retry-platform",
      cwd: "apps/pythias-platform",
      script: "scripts/runDropshipRetry.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "20 * * * *", // hourly at :20 — re-attempt dropship orders left needs_funding
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3010,
      },
      out_file: "logs/dropship-retry-platform-out.log",
      error_file: "logs/dropship-retry-platform-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-payout-reconcile",
      cwd: "apps/pythias-storefront",
      script: "scripts/runPayoutReconcile.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "30 * * * *", // every hour at :30 — settle any shipped storefront orders whose payout is still pending
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3020,
      },
      out_file: "logs/storefront-payout-reconcile-out.log",
      error_file: "logs/storefront-payout-reconcile-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-outbox",
      cwd: "apps/pythias-storefront",
      script: "scripts/runOutbox.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "*/3 * * * *", // every 3 min — drains email/SMS outbox (batch × interval = send rate, low for reputation)
      watch: false,
      env: { NODE_ENV: "production", PORT: 3020 },
      out_file: "logs/storefront-outbox-out.log",
      error_file: "logs/storefront-outbox-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-lifecycle",
      cwd: "apps/pythias-storefront",
      script: "scripts/runLifecycle.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "15 * * * *", // hourly — enqueue abandoned-cart / abandoned-session nudges
      watch: false,
      env: { NODE_ENV: "production", PORT: 3020 },
      out_file: "logs/storefront-lifecycle-out.log",
      error_file: "logs/storefront-lifecycle-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-marketing-billing",
      cwd: "apps/pythias-platform",
      script: "scripts/runMarketingBilling.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 6 1 * *", // 06:00 UTC on the 1st — bills last month's email/SMS overage as invoice items
      watch: false,
      env: { NODE_ENV: "production", PORT: 3010 },
      out_file: "logs/storefront-marketing-billing-out.log",
      error_file: "logs/storefront-marketing-billing-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-weekly-report",
      cwd: "apps/pythias-platform",
      script: "scripts/runWeeklyReport.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 13 * * 1", // Mondays 13:00 UTC (~9am ET) — email sellers their weekly store report
      watch: false,
      env: { NODE_ENV: "production", PORT: 3010 },
      out_file: "logs/storefront-weekly-report-out.log",
      error_file: "logs/storefront-weekly-report-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-adspend",
      cwd: "apps/pythias-platform",
      script: "scripts/runAdSpendSync.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "30 9 * * *", // daily 09:30 UTC — pull Google Ads spend into channel ROI
      watch: false,
      env: { NODE_ENV: "production", PORT: 3010 },
      out_file: "logs/storefront-adspend-out.log",
      error_file: "logs/storefront-adspend-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-demand",
      cwd: "apps/pythias-platform",
      script: "scripts/runDemandForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 10 * * *", // daily 10:00 UTC — refresh AI demand curves + auto-restock (before autopilot at 11:00)
      watch: false,
      env: { NODE_ENV: "production", PORT: 3010 },
      out_file: "logs/storefront-demand-out.log",
      error_file: "logs/storefront-demand-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-autopilot",
      cwd: "apps/pythias-platform",
      script: "scripts/runAutopilot.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 11 * * *", // daily 11:00 UTC (~7am ET) — autonomous autopilot for opted-in stores
      watch: false,
      env: { NODE_ENV: "production", PORT: 3010 },
      out_file: "logs/storefront-autopilot-out.log",
      error_file: "logs/storefront-autopilot-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "storefront-subscriptions",
      cwd: "apps/pythias-storefront",
      script: "scripts/runSubscriptions.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "45 */6 * * *", // every 6h — bill due subscribe-&-save subscriptions
      watch: false,
      env: { NODE_ENV: "production", PORT: 3020 },
      out_file: "logs/storefront-subscriptions-out.log",
      error_file: "logs/storefront-subscriptions-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "generate-invoices",
      cwd: "apps/pythias",
      script: "scripts/runGenerateInvoices.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 9 1 * *", // 1st of every month at 9am UTC (4am EST)
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      out_file: "logs/generate-invoices-out.log",
      error_file: "logs/generate-invoices-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "product-update-email",
      cwd: "apps/pythias",
      script: "scripts/runProductUpdate.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 16 1 * *", // 1st of every month at 16:00 UTC (11am EST) — after monthly-broadcast
      watch: false,
      env: { NODE_ENV: "production", PORT: 3002 },
      out_file: "logs/product-update-out.log",
      error_file: "logs/product-update-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "monthly-broadcast",
      cwd: "apps/pythias",
      script: "scripts/runMonthlyBroadcast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 15 1 * *", // 1st of every month at 15:00 UTC (10am EST)
      watch: false,
      env: { NODE_ENV: "production", PORT: 3002 },
      out_file: "logs/monthly-broadcast-out.log",
      error_file: "logs/monthly-broadcast-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "marketing-emails",
      cwd: "apps/pythias",
      script: "scripts/runMarketingEmails.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 15 * * *", // every day at 15:00 UTC (10am EST)
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      out_file: "logs/marketing-emails-out.log",
      error_file: "logs/marketing-emails-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "chronos-forecaster",
      cwd: "services/chronos-forecaster",
      script: "start.sh",
      interpreter: "bash",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      out_file: "logs/chronos-out.log",
      error_file: "logs/chronos-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      min_uptime: "60s",
      max_restarts: 5,
    },
    {
      name: "embroidery-service",
      cwd: "services/embroidery",
      script: "start.sh",
      interpreter: "bash",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      out_file: "logs/embroidery-out.log",
      error_file: "logs/embroidery-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      min_uptime: "10s",
      max_restarts: 5,
    },
  ],
};
  