module.exports = {
  apps: [
    {
      name: "nextjs-premier",
      cwd: "apps/premier-printing",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      exec_mode: "cluster",
      instances: "5",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "3",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-pythias",
      cwd: "apps/pythias",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3002",
      exec_mode: "cluster",
      instances: "1",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "10",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-printthreads",
      cwd: "apps/printthreads",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3003",
      exec_mode: "cluster",
      instances: "1",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "10",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    {
      name: "nextjs-po",
      cwd: "apps/po",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      exec_mode: "cluster",
      instances: "5",
      env: {
        NODE_ENV: "production",
        LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
      },
      output: null, // Output log file
      error: null, // Error log file
      merge_logs: true,
      log_rotate: true,
      max_size: "10M",
      retain: "10",
      log_date_format: "YYYY-MM-DD HH:mm Z",

      max_memory_restart: "5G",
      max_restarts: 10,
      min_uptime: "30s",
      cron_restart: "0 9 * * *", //9am UTC is 4AM EST
    },
    // {
    //   name: "nextjs-platform",
    //   cwd: "apps/pythias-platform",
    //   script: "node_modules/next/dist/bin/next",
    //   args: "start -p 3010",
    //   exec_mode: "cluster",
    //   instances: "2",
    //   env: {
    //     NODE_ENV: "production",
    //     LD_LIBRARY_PATH: "/home/michaelthero/pythias/node_modules/@img/sharp-libvips-linux-x64/lib",
    //   },
    //   output: null,
    //   error: null,
    //   merge_logs: true,
    //   log_rotate: true,
    //   max_size: "10M",
    //   retain: "3",
    //   log_date_format: "YYYY-MM-DD HH:mm Z",
    //   max_memory_restart: "3G",
    //   max_restarts: 10,
    //   min_uptime: "30s",
    //   cron_restart: "0 9 * * *",
    // },
    {
      name: "pull-orders",
      cwd: "apps/premier-printing",
      script: "scripts/runPullOrders.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 * * * *", // every hour
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/pull-orders-out.log",
      error_file: "logs/pull-orders-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "tracking-premier-printing",
      cwd: "apps/premier-printing",
      script: "scripts/runTracking.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */6 * * *", // every 6 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/tracking-premier-out.log",
      error_file: "logs/tracking-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "tracking-po",
      cwd: "apps/po",
      script: "scripts/runTracking.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */6 * * *", // every 6 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/tracking-po-out.log",
      error_file: "logs/tracking-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "blanks-forecast-premier",
      cwd: "apps/premier-printing",
      script: "scripts/runBlankForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/blanks-forecast-premier-out.log",
      error_file: "logs/blanks-forecast-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "blanks-forecast-printthreads",
      cwd: "apps/printthreads",
      script: "scripts/runBlankForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      out_file: "logs/blanks-forecast-printthreads-out.log",
      error_file: "logs/blanks-forecast-printthreads-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "blanks-forecast-po",
      cwd: "apps/po",
      script: "scripts/runBlankForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/blanks-forecast-po-out.log",
      error_file: "logs/blanks-forecast-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "forecast-premier",
      cwd: "apps/premier-printing",
      script: "scripts/runForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      out_file: "logs/forecast-premier-out.log",
      error_file: "logs/forecast-premier-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "forecast-printthreads",
      cwd: "apps/printthreads",
      script: "scripts/runForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      out_file: "logs/forecast-printthreads-out.log",
      error_file: "logs/forecast-printthreads-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "forecast-po",
      cwd: "apps/po",
      script: "scripts/runForecast.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 */4 * * *", // every 4 hours
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      out_file: "logs/forecast-po-out.log",
      error_file: "logs/forecast-po-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "generate-invoices",
      cwd: "apps/pythias",
      script: "scripts/runGenerateInvoices.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      cron_restart: "0 9 1 * *", // 1st of every month at 9am UTC (4am EST)
      watch: false,
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      out_file: "logs/generate-invoices-out.log",
      error_file: "logs/generate-invoices-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
    },
    {
      name: "chronos-forecaster",
      cwd: "services/chronos-forecaster",
      script: "start.sh",
      interpreter: "bash",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      out_file: "logs/chronos-out.log",
      error_file: "logs/chronos-error.log",
      merge_logs: false,
      log_date_format: "YYYY-MM-DD HH:mm Z",
      min_uptime: "60s",
      max_restarts: 5,
    },
  ],
};
  