export const dynamic = "force-dynamic";
import { NextResponse } from "next/server";
import { StorefrontRestockTask } from "@pythias/mongo";
import { storefront } from "@pythias/backend/server";
import { sendEmail } from "@/lib/email";

// POST /api/internal/demand/run — refresh AI demand curves + auto-restock for every store,
// then email suppliers for any auto-created reorders. Driven daily by PM2. Shared-secret guarded.
export async function POST(req) {
    if (!process.env.PYTHIAS_INTERNAL_KEY || req.headers.get("x-pythias-internal-key") !== process.env.PYTHIAS_INTERNAL_KEY) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    try {
        const r = await storefront.runAllDemandForecasts();
        let emailed = 0;
        for (const n of r.notify || []) {
            try {
                const res = await sendEmail({
                    to: n.supplierEmail,
                    subject: `Reorder request — ${n.qty} × ${n.title || "product"}`,
                    html: `<div style="font-family:Arial,sans-serif"><p>Please prepare a reorder:</p><p><b>${n.qty}</b> × <b>${n.title || "product"}</b></p><p style="color:#64748b;font-size:12px">Automatically generated by Pythias autopilot based on projected demand.</p></div>`,
                });
                if (res?.ok !== false) { emailed++; await StorefrontRestockTask.updateOne({ _id: n.taskId }, { $set: { supplierNotified: true } }); }
            } catch { /* leave task un-notified; seller can resend */ }
        }
        return NextResponse.json({ error: false, ...r, emailed });
    } catch (e) { return NextResponse.json({ error: e.message }, { status: 500 }); }
}
